name: Continuous integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: cp -r package.json yarn.lock doc dist/
      - uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
